In [ ]:
import os
import pandas as pd

In [2]:
path = os.getcwd()
src_path = os.path.join(path, "data_src")

In [3]:
src_path

'c:\\Users\\alvar\\repos\\GitHub\\JCRFECYT\\data_src'

In [7]:
csv_files = [
    f for f in os.listdir(src_path)
    if os.path.isfile(os.path.join(src_path, f)) and f.lower().endswith('.csv')
]

In [8]:
csv_files

['2025_cs_artificial_intelligence.csv',
 '2025_cs_cs_information_systems.csv',
 '2025_cs_interdisciplinary_applications.csv',
 '2025_engineering_biomedical.csv',
 '2025_medical_informatics.csv']

In [11]:
iaeav_file = csv_files[4]

In [12]:
file_tmp = os.path.join(src_path, iaeav_file)

In [13]:
file_tmp

'c:\\Users\\alvar\\repos\\GitHub\\JCRFECYT\\data_src\\2025_medical_informatics.csv'

In [22]:
df = pd.read_csv(file_tmp, skiprows=2)[:-2]

In [25]:
df

,Journal name,JCR Abbreviation,Publisher,ISSN,eISSN,Category,Edition,Total Citations,1998 JIF,JIF Quartile,1998 JCI,% of Citable OA
JOURNAL OF THE AMERICAN MEDICAL INFORMATICS ASSOCIATION,J AM MED INFORM ASSN,HANLEY & BELFUS INC,1067-5027,1527-974X,MEDICAL INFORMATICS,SCIE,545,2.462,Q1,NaN,NaN,NaN
MEDICAL DECISION MAKING,MED DECIS MAKING,HANLEY & BELFUS INC,0272-989X,1552-681X,MEDICAL INFORMATICS,SCIE,"1,155",2.125,Q1,NaN,NaN,NaN
MEDICAL INFORMATICS,MED INFORM,TAYLOR & FRANCIS LTD,0307-7640,NaN,MEDICAL INFORMATICS,SCIE,258,1.614,Q1,NaN,NaN,NaN
INTERNATIONAL JOURNAL OF TECHNOLOGY ASSESSMENT IN HEALTH CARE,INT J TECHNOL ASSESS,CAMBRIDGE UNIV PRESS,0266-4623,1471-6348,MEDICAL INFORMATICS,SCIE,661,1.385,Q1,NaN,NaN,NaN
STATISTICS IN MEDICINE,STAT MED,JOHN WILEY & SONS LTD,0277-6715,1097-0258,MEDICAL INFORMATICS,SCIE,"3,252",1.177,Q1,NaN,NaN,NaN
ACADEMIC MEDICINE,ACAD MED,HANLEY & BELFUS INC,1040-2446,1938-808X,MEDICAL INFORMATICS,SCIE,"2,272",1.126,Q2,NaN,NaN,NaN
M D COMPUTING,M D COMPUT,SPRINGER VERLAG,0724-6811,NaN,MEDICAL INFORMATICS,SCIE,204,1.033,Q2,NaN,NaN,NaN
ARTIFICIAL INTELLIGENCE IN MEDICINE,ARTIF INTELL MED,ELSEVIER SCIENCE BV,0933-3657,1873-2860,MEDICAL INFORMATICS,SCIE,215,1.015,Q2,NaN,NaN,NaN
MEDICAL & BIOLOGICAL ENGINEERING & COMPUTING,MED BIOL ENG COMPUT,PETER PEREGRINUS LTD,0140-0118,1741-0444,MEDICAL INFORMATICS,SCIE,"1,561",0.856,Q2,NaN,NaN,NaN
COMPUTERS AND BIOMEDICAL RESEARCH,COMPUT BIOMED RES,ACADEMIC PRESS INC JNL-COMP SUBSCRIPTIONS,0010-4809,NaN,MEDICAL INFORMATICS,SCIE,537,0.836,Q2,NaN,NaN,NaN
IEEE ENGINEERING IN MEDICINE AND BIOLOGY MAGAZINE,IEEE ENG MED BIOL,IEEE-INST ELECTRICAL ELECTRONICS ENGINEERS INC,0739-5175,1937-4186,MEDICAL INFORMATICS,SCIE,370,0.786,Q3,NaN,NaN,NaN
MEDICAL EDUCATION,MED EDUC,BLACKWELL SCIENCE LTD,0308-0110,1365-2923,MEDICAL INFORMATICS,SCIE,990,0.716,Q3,NaN,NaN,NaN
COMPUTER METHODS AND PROGRAMS IN BIOMEDICINE,COMPUT METH PROG BIO,NaN,0169-2607,1872-7565,MEDICAL INFORMATICS,SCIE,673,0.664,Q3,NaN,NaN,NaN
METHODS OF INFORMATION IN MEDICINE,METHOD INFORM MED,F K SCHATTAUER VERLAG GMBH,0026-1270,2511-705X,MEDICAL INFORMATICS,SCIE,581,0.651,Q3,NaN,NaN,NaN
BIOMEDIZINISCHE TECHNIK,BIOMED TECH,FACHVERLAG SCHIELE SCHON,0013-5585,1862-278X,MEDICAL INFORMATICS,SCIE,230,0.441,Q3,NaN,NaN,NaN
INTERNATIONAL JOURNAL OF BIO-MEDICAL COMPUTING,INT J BIOMED COMPUT,NaN,0020-7101,NaN,MEDICAL INFORMATICS,SCIE,327,0.403,Q4,NaN,NaN,NaN
JOURNAL OF MEDICAL ENGINEERING & TECHNOLOGY,J MED ENG TECHNOL,TAYLOR & FRANCIS LTD,0309-1902,1464-522X,MEDICAL INFORMATICS,SCIE,166,0.383,Q4,NaN,NaN,NaN
INTERNATIONAL JOURNAL OF MEDICAL INFORMATICS,INT J MED INFORM,NaN,1386-5056,1872-8243,MEDICAL INFORMATICS,SCIE,34,0.375,Q4,NaN,NaN,NaN
INTERNATIONAL JOURNAL OF CLINICAL MONITORING AND COMPUTING,INT J CLIN MONIT COM,KLUWER ACADEMIC PUBL,0167-9945,NaN,MEDICAL INFORMATICS,SCIE,121,0.241,Q4,NaN,NaN,NaN
JOURNAL OF CLINICAL MONITORING AND COMPUTING,J CLIN MONITOR COMP,KLUWER ACADEMIC PUBL,1387-1307,NaN,MEDICAL INFORMATICS,SCIE,4,NaN,Q4,NaN,NaN,NaN

In [28]:
df[["JCR Abbreviation", "Category", "1998 JIF"]]

,JCR Abbreviation,Category,1998 JIF
JOURNAL OF THE AMERICAN MEDICAL INFORMATICS ASSOCIATION,HANLEY & BELFUS INC,SCIE,Q1
MEDICAL DECISION MAKING,HANLEY & BELFUS INC,SCIE,Q1
MEDICAL INFORMATICS,TAYLOR & FRANCIS LTD,SCIE,Q1
INTERNATIONAL JOURNAL OF TECHNOLOGY ASSESSMENT IN HEALTH CARE,CAMBRIDGE UNIV PRESS,SCIE,Q1
STATISTICS IN MEDICINE,JOHN WILEY & SONS LTD,SCIE,Q1
ACADEMIC MEDICINE,HANLEY & BELFUS INC,SCIE,Q2
M D COMPUTING,SPRINGER VERLAG,SCIE,Q2
ARTIFICIAL INTELLIGENCE IN MEDICINE,ELSEVIER SCIENCE BV,SCIE,Q2
MEDICAL & BIOLOGICAL ENGINEERING & COMPUTING,PETER PEREGRINUS LTD,SCIE,Q2
COMPUTERS AND BIOMEDICAL RESEARCH,ACADEMIC PRESS INC JNL-COMP SUBSCRIPTIONS,SCIE,Q2
IEEE ENGINEERING IN MEDICINE AND BIOLOGY MAGAZINE,IEEE-INST ELECTRICAL ELECTRONICS ENGINEERS INC,SCIE,Q3
MEDICAL EDUCATION,BLACKWELL SCIENCE LTD,SCIE,Q3
COMPUTER METHODS AND PROGRAMS IN BIOMEDICINE,NaN,SCIE,Q3
METHODS OF INFORMATION IN MEDICINE,F K SCHATTAUER VERLAG GMBH,SCIE,Q3
BIOMEDIZINISCHE TECHNIK,FACHVERLAG SCHIELE SCHON,SCIE,Q3
INTERNATIONAL JOURNAL OF BIO-MEDICAL COMPUTING,NaN,SCIE,Q4
JOURNAL OF MEDICAL ENGINEERING & TECHNOLOGY,TAYLOR & FRANCIS LTD,SCIE,Q4
INTERNATIONAL JOURNAL OF MEDICAL INFORMATICS,NaN,SCIE,Q4
INTERNATIONAL JOURNAL OF CLINICAL MONITORING AND COMPUTING,KLUWER ACADEMIC PUBL,SCIE,Q4
JOURNAL OF CLINICAL MONITORING AND COMPUTING,KLUWER ACADEMIC PUBL,SCIE,Q4